# Generated by Django 2.0.5 on 2020-05-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20200519_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='nums',
            new_name='jidu_1',
        ),
        migrations.RemoveField(
            model_name='data',
            name='jidu',
        ),
        migrations.AddField(
            model_name='data',
            name='jidu_2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='jidu_3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='jidu_4',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='year',
            field=models.CharField(default='', max_length=4),
        ),
    ]
