# Generated by Django 2.1.7 on 2020-05-24 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_auto_20200524_0900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['-add_time']},
        ),
    ]
